# Generated by Django 2.2 on 2020-02-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
