# Generated by Django 2.2 on 2020-02-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_form_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='title',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
