# Generated by Django 2.2 on 2020-02-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_form_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='public',
            field=models.BooleanField(default='ask'),
        ),
    ]
