# Generated by Django 2.2 on 2020-02-12 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20200210_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='public',
        ),
        migrations.RemoveField(
            model_name='form',
            name='title',
        ),
    ]
